apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-go-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-go-service
  template:
    metadata:
      labels:
         app: sample-go-service
    spec:
      containers:
        - name: sample-go-service
          image: public.ecr.aws/mock-node-api/lowsandbox:sample-go-api
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_SERVICE
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName
          livenessProbe:
            httpGet:
              path: /health
              port:  8080
            initialDelaySeconds: 5
            periodSeconds: 5
          envFrom:
            - configMapRef:
                name: dev-env
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080

